sudo: false

language: python

python:
  - "3.5"

services:
  - docker

before_install:
  - export DJANGO_SETTINGS_MODULE="CioYardSale.settings"
  - export PYTHONPATH="$HOME/builds/emmafass/app"
  - docker pull tp33/django
  - docker pull mysql:5.7.14
  - mkdir ~/cs4501
  - mkdir ~/cs4501/app
  - docker run --memory 4g --name web -v ~/cs4501/app:/app tp33/django
  - mkdir ~/cs4501/db
  - docker run --memory 4g --name mysql -d -e MYSQL\_ROOT\_PASSWORD='$3cureUS' -v ~/cs4501/db:/var/lib/mysql mysql:5.7.14
  - sleep 20
  - docker run -it --name mysql-cmdline --link mysql:db mysql:5.7.14 mysql -uroot -p'$3cureUS' -h db -e "create user 'www'@'%' identified by '\$3cureUS'; CREATE DATABASE cs4501; grant all on test_cs4501.* to 'www'@'%'; grant all on cs4501.* to 'www'@'%';"

before-script:
  - docker start mysql
  - docker-compose up -d
  - sleep 20

script:
  - docker exec -it cioyardsale_models_1 bash -c "python ./manage.py test --no-input commodity"
