models:
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - ./app/CioYardSale:/app
    ports:
      - "8001:8000"
    command: bash -c "mod_wsgi-express start-server --working-directory ./app/CioYardSale --reload-on-changes ./app/CioYardSale/CioYardSale/wsgi.py"
