models:
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - ./CioYardSale:/app
    ports:
      - "8001:8000"
    command: bash -c "pip install Pillow && pip install requests && python manage.py makemigrations myUser && python manage.py makemigrations cio && python manage.py makemigrations commodity && python manage.py migrate commodity && python manage.py migrate cio && python manage.py migrate myUser && python manage.py loaddata db-commodities-2.json && mod_wsgi-express start-server --reload-on-changes --working-directory ./ ./CioYardSale/wsgi.py"

exp:
   image: tp33/django
   links:
      - models:models-api
      - kafka:kafka
      - es:es
   volumes:
      - ./exp:/app
   ports:
      - "8002:8000"
   command: "mod_wsgi-express start-server --reload-on-changes ./exp/wsgi.py"

web:
   image: tp33/django
   links:
      - exp:exp-api
   volumes:
      - ./web:/app
   ports:
      - "8003:8000"
   command: bash -c "pip install requests && mod_wsgi-express start-server --reload-on-changes ./web/wsgi.py"

kafka:
   image: spotify/kafka
   container_name: kafka
   environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
   hostname: kafka

es:
   image: elasticsearch:2.0
   container_name: es
   ports:
      - "9200:9200"

batch:
   image: tp33/django
   container_name: batch
   volumes:
      - ./batch:/app
   links:
      - kafka:kafka
      - es:es
   command: bash -c "python kafkaconsumer.py"

batch_recommendation:
   image: tp33/django
   container_name: batch_recommendation
   volumes:
      - ./batch_recommendation:/app
      - ./data:/app2
   links:
      - kafka:kafka
      - es:es
   command: bash -c "python kafka_recommendations.py"

web2:
   image: tp33/django
   links:
      - exp:exp-api
   volumes:
      - ./web:/app
   ports:
      - "8004:8000"
   command: bash -c "pip install requests && mod_wsgi-express start-server --reload-on-changes ./web/wsgi.py"

haproxy:
  image: haproxy
  container_name: haproxy
  links:
    - web:web
    - web2:web2
  volumes:
    - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
  ports:
    - "8000:8000"

selenium-chrome:
  image: selenium/standalone-chrome
  container_name: selenium-chrome
  links:
    - web:web
  ports:
    - "4444:4444"

selenium-test:
  image: tp33/django
  container_name: selenium-test
  links:
    - selenium-chrome:selenium-chrome
    - web:web
  volumes:
    - ./selenium:/app
  command: bash -c "pip install selenium==3.11.0 && python selenium-tests.py"

spark-master:
  image: gettyimages/spark
  external_links:
    - mysql:db
  command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
  container_name: spark-master
  hostname: spark-master
  environment:
    MASTER: spark://spark-master:7077
    SPARK_CONF_DIR: /conf
  expose:
    - 7001
    - 7002
    - 7003
    - 7004
    - 7005
    - 7006
    - 7077
    - 6066
  ports:
    - 4040:4040
    - 6066:6066
    - 7077:7077
    - 8080:8080
  volumes:
    - ./data:/tmp/data

spark-worker:
  image: gettyimages/spark
  external_links:
    - mysql:db
  command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
  container_name: spark-worker
  hostname: spark-worker
  environment:
    SPARK_CONF_DIR: /conf
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 512m
    SPARK_WORKER_PORT: 8881
    SPARK_WORKER_WEBUI_PORT: 8081
  links:
    - spark-master
  expose:
    - 7012
    - 7013
    - 7014
    - 7015
    - 7016
    - 8881
  ports:
    - 8081:8081
  volumes:
    - ./data:/tmp/data
