models:
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - ./:/app
    ports:
      - "8001:8000"
    command: bash -c "pip install Pillow && python manage.py loaddata database.json && mod_wsgi-express start-server --reload-on-changes --working-directory ./ ./CioYardSale/wsgi.py"
