models:
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - ./CioYardSale:/app
    ports:
      - "8001:8000"
    command: bash -c "pip install Pillow && pip install requests && python manage.py loaddata db-users-and-items.json && mod_wsgi-express start-server --reload-on-changes --working-directory ./ ./CioYardSale/wsgi.py"

exp:
   image: tp33/django
   links:
      - models:models-api
      - kafka:kafka
      - es:es
   volumes:
      - ./exp:/app
   ports:
      - "8002:8000"
   command: "mod_wsgi-express start-server --reload-on-changes ./exp/wsgi.py"

web:
   image: tp33/django
   links:
      - exp:exp-api
   volumes:
      - ./web:/app
   ports:
      - "8003:8000"
   command: bash -c "pip install requests && mod_wsgi-express start-server --reload-on-changes ./web/wsgi.py"

kafka:
   image: spotify/kafka
   container_name: kafka
   environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
   hostname: kafka

es:
   image: elasticsearch:2.0
   container_name: es
   ports:
      - "9200:9200"

batch:
   image: tp33/django
   container_name: batch
   volumes:
      - ./batch:/app
   links:
      - kafka:kafka
      - es:es
   command: bash -c "python kafkaconsumer.py"

web2:
   image: tp33/django
   links:
      - exp:exp-api
   volumes:
      - ./web:/app
   ports:
      - "8004:8000"
   command: bash -c "pip install requests && mod_wsgi-express start-server --reload-on-changes /app/web/wsgi.py"

haproxy:
  image: haproxy
  container_name: haproxy
  links:
    - web:web
    - web2:web2
  volumes:
    - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
  ports:
    - "8000:8000"

selenium-chrome:
  image: selenium/standalone-chrome
  container_name: selenium-chrome
  links:
    - web:web
  ports:
    - "4444:4444"

selenium-test:
  image: tp33/django
  container_name: selenium-test
  links:
    - selenium-chrome:selenium-chrome
    - web:web
  volumes:
    - ./app/selenium:/app
  command: bash -c "pip install selenium==3.11.0 && python selenium-tests.py"
