models:
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - ./CioYardSale:/app
    ports:
      - "8001:8000"
    command: bash -c "pip install Pillow && python manage.py loaddata database.json && mod_wsgi-express start-server --reload-on-changes --working-directory ./ ./CioYardSale/wsgi.py"

exp:
   image: tp33/django
   links:
      - models:models-api
   volumes:
      - ./exp:/app
   ports:
      - "8002:8000"
   command: "mod_wsgi-express start-server --reload-on-changes ./exp/wsgi.py"

web:
   image: tp33/django
   links:
      - exp:exp-api
   volumes:
      - ./web:/app
   ports:
      - "8000:8000"
   command: "mod_wsgi-express start-server --reload-on-changes ./web/wsgi.py"
